# Generated by Django 2.2.6 on 2019-12-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20191210_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='queston',
            field=models.ManyToManyField(through='exam.QuestionGroup', to='exam.Question'),
        ),
    ]
