# Generated by Django 2.2.6 on 2019-12-17 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20191214_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='queston',
            new_name='question',
        ),
    ]
