# Generated by Django 2.2.6 on 2019-12-17 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_selectedchoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedchoices',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_choice', to='exam.Choice'),
        ),
    ]
