# Generated by Django 2.2.6 on 2019-12-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20191217_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedchoices',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='selectedchoices',
            name='question',
        ),
        migrations.RemoveField(
            model_name='selectedchoices',
            name='user',
        ),
        migrations.AddField(
            model_name='selectedchoices',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
