# Generated by Django 2.2.6 on 2019-12-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20191217_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='total_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
