# Generated by Django 2.2.6 on 2019-12-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_auto_20191218_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='total_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
